### ISSUE TITLE
jddb?

### ISSUE THREAD

**Issue by cibersheep** [Utodev/jDAAD#2]
Hola.
¿Se puede convertir una DDB en jddb? ¿Cómo?

**Comment by Utodev** [comment]
El jddb es meramente la representación en un array javascript del binario del DDB, de hecho, el compilador de DAAD Ready genera el DDB, y al final si el target es HTML, genera el jddb.

No obstante hay dos problemas, si lo que pretendes es usar el DDB de algo que ya está hecho para ponerlo en HTML:

1) el segundo byte de un DDB indica para qué máquina es, una vez convertido el DDB tienes que cambiar el segundo byte por 0xD1.

2) Los DDB no son ficheros portables. Se generan para la máquina objetivo y el DDB de una máquina no vale para otra, fundamentalmente porque incluyen punteros estáticos a direcciones en el rango 0-65535 que dependen de la máquina. Por suerte, el target HTML comparte modelo de memoria con los targets de DOS, Amiga y AtariST, por lo que si pasar un DDB a HTML puede funcionar, será con un DDB de esas máquinas. Con los otros fallará.


Finalmente comentar que jDAAD es bastante nuevo, seguramente aun hay bugs, por lo que puede que el juego no funcione bien en algun punto pero no por culpa de la conversión del DDB a jDDB.

**Comment by cibersheep** [comment]
Entiendo.
Gracias por la explicación <3
